baseURL = "https://vaga.io"
defaultContentLanguage = "fr"
title = "vaga.io"
theme = "m10c"

[params]
  # Author
  author = "Fabien CASTERS"
  # Description
  description = "I write code and I take care about my privacy // Co-founder @ Owaka // Golang lover // Open source enthusiast"
  # Social links
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/vaga"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/vaga_io"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/fabien-casters/"
