baseURL = "https://vaga.io"
defaultContentLanguage = "fr"
title = "vaga.io"
theme = "m10c"

[params]
  # Author
  author = "Fabien CASTERS"
  # Description
  description = "Bonjour ! Je suis devops chez +Simple et je suis passionne par l'open source et les nouvelles technologies."
  # Social links
  [[params.social]]
    name = "github"
    url = "https://github.com/vaga"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/vaga_io"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/fabien-casters/"
